FROM anterondocker/sparse-framework:pytorch

COPY requirements_graphs.txt requirements_graphs.txt
RUN pip install -r requirements_graphs.txt

WORKDIR /app
COPY sparse_framework sparse_framework

CMD ["python", "-m", "sparse_framework.utils.plotting"]
