---
apiVersion: batch/v1
kind: Job
metadata:
  name: inference-aio
  namespace: sparse
  labels:
    app: inference-aio
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: sparse/node
                operator: In
                values:
                - aio
      containers:
      - name: inference-aio
        image: split_inference
        imagePullPolicy: IfNotPresent
        command: ["python3"]
        args: ["benchmark.py", "--suite", "aio", "--dataset", "Imagenet100"]
        volumeMounts:
        - name: app-code
          mountPath: /app
        - name: sparse-code
          mountPath: /usr/lib/sparse_framework
        - name: sparse-data
          mountPath: /data
        - name: sparse-run
          mountPath: /run/sparse
      restartPolicy: Never
      volumes:
      - name: app-code
        hostPath:
          path: /opt/sparse/examples/split_inference
      - name: sparse-code
        hostPath:
          path: /opt/sparse/sparse_framework
      - name: sparse-data
        hostPath:
          path: /var/lib/sparse/data
      - name: sparse-run
        hostPath:
          path: /run/sparse
