---
apiVersion: batch/v1
kind: Job
metadata:
  name: learning-datasource
  namespace: sparse
  labels:
    app: learning-datasource
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: sparse/node
                operator: In
                values:
                - datasource
                - aio
      containers:
      - name: learning-datasource
        image: split_learning
        imagePullPolicy: IfNotPresent
        env:
        - name: MASTER_UPSTREAM_HOST
          value: "learning-split-intermediate"
        command: ["python3"]
        args: ["benchmark.py", "--suite", "offload_source", "--batches", "64", "--batch-size", "64", "--dataset", "CIFAR100"]
        volumeMounts:
        - name: app-code
          mountPath: /app
        - name: sparse-code
          mountPath: /usr/lib/sparse_framework
        - name: sparse-data
          mountPath: /data
        - name: sparse-run
          mountPath: /run/sparse
      restartPolicy: Never
      volumes:
      - name: app-code
        hostPath:
          path: /opt/sparse/examples/split_learning
      - name: sparse-code
        hostPath:
          path: /opt/sparse/sparse_framework
      - name: sparse-data
        hostPath:
          path: /var/lib/sparse/data
      - name: sparse-run
        hostPath:
          path: /run/sparse
