---
apiVersion: batch/v1
kind: Job
metadata:
  name: learning-aio
  namespace: sparse
  labels:
    app: learning-aio
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: sparse/node
                operator: In
                values:
                - aio
      containers:
      - name: learning-aio
        image: split_learning
        imagePullPolicy: IfNotPresent
        command: ["python3"]
        args:
        - "learning_aio.py"
        - "--suite"
        - "$SPARSE_SUITE"
        - "--model"
        - "$SPARSE_MODEL"
        - "--dataset"
        - "$SPARSE_DATASET"
        - "--batch-size"
        - "$SPARSE_BATCH_SIZE"
        - "--batches"
        - "$SPARSE_BATCHES"
        - "--deprune-props"
        - "$SPARSE_DEPRUNE_PROPS"
        - "--feature_compression_factor"
        - "$FEATURE_COMPRESSION_FACTOR"
        - "--resolution_compression_factor"
        - "$RESOLUTION_COMPRESSION_FACTOR"
        - "--epochs"
        - "$SPARSE_EPOCHS"
        volumeMounts:
        - name: app-code
          mountPath: /app
        - name: sparse-code
          mountPath: /usr/lib/sparse_framework
        - name: sparse-data
          mountPath: /data
        - name: sparse-run
          mountPath: /run/sparse
      restartPolicy: Never
      volumes:
      - name: app-code
        hostPath:
          path: /opt/sparse/examples/split_learning
      - name: sparse-code
        hostPath:
          path: /opt/sparse/sparse_framework
      - name: sparse-data
        hostPath:
          path: /var/lib/sparse/data
      - name: sparse-run
        hostPath:
          path: /run/sparse
