---
apiVersion: v1
kind: Service
metadata:
  name: learning-worker
  namespace: sparse
  labels:
    app: learning-worker
spec:
  ports:
  - port: 50007
    protocol: TCP
  selector:
    app: learning-worker

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-worker
  namespace: sparse
  labels:
    app: learning-worker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: learning-worker
  template:
    metadata:
      labels:
        app: learning-worker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: sparse/node
                operator: In
                values:
                - worker
                - aio
      containers:
      - name: learning-worker
        image: split_learning
        imagePullPolicy: IfNotPresent
        env:
        - name: WORKER_LISTEN_ADDRESS
          value: "0.0.0.0"
        command: ["python3"]
        args:
        - "learning_worker.py"
        - "--suite"
        - "$SPARSE_SUITE"
        - "--model"
        - "$SPARSE_MODEL"
        - "--dataset"
        - "$SPARSE_DATASET"
        - "--batch-size"
        - "$SPARSE_BATCH_SIZE"
        - "--batches"
        - "$SPARSE_BATCHES"
        - "--deprune-props"
        - "$SPARSE_DEPRUNE_PROPS"
        volumeMounts:
        - name: app-code
          mountPath: /app
        - name: sparse-code
          mountPath: /usr/lib/sparse_framework
        - name: sparse-run
          mountPath: /run/sparse
      volumes:
      - name: app-code
        hostPath:
          path: /opt/sparse/examples/split_learning
      - name: sparse-code
        hostPath:
          path: /opt/sparse/sparse_framework
      - name: sparse-run
        hostPath:
          path: /run/sparse
