---
apiVersion: batch/v1
kind: Job
metadata:
  name: learning-split-source
  namespace: sparse
  labels:
    app: learning-split-source
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: sparse/node
                operator: In
                values:
                - datasource
                - aio
      containers:
      - name: learning-split-source
        image: split_learning
        imagePullPolicy: IfNotPresent
        env:
        - name: MASTER_UPSTREAM_HOST
          value: "learning-unsplit-final"
        command: ["python3"]
        args: ["benchmark.py", "--suite", "offload_source", "--batches", "64", "--batch-size", "64"]
        volumeMounts:
        - name: sparse-data
          mountPath: /data
        - name: sparse-run
          mountPath: /run/sparse
      restartPolicy: Never
      volumes:
      - name: sparse-data
        hostPath:
          path: /var/lib/sparse/data
      - name: sparse-run
        hostPath:
          path: /run/sparse
