---
apiVersion: batch/v1
kind: Job
metadata:
  name: learning-split-ondevice-client
  namespace: sparse
  labels:
    app: learning-split-ondevice-client
spec:
  template:
    metadata:
      labels:
        app: learning-split-ondevice-client
    spec:
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: sparse/node
                operator: In
                values:
                - datasource
                - aio
      containers:
      - name: learning-split-ondevice-client
        image: split_learning
        imagePullPolicy: IfNotPresent
        env:
        - name: MASTER_UPSTREAM_HOST
          value: "learning-split-ondevice-final"
        command: ["python3"]
        args: ["benchmark.py", "--suite", "offload_client", "--model", "VGG_client", "--batches", "64", "--batch-size", "64",
              "--dataset", "CIFAR10"]
        volumeMounts:
        - name: app-code
          mountPath: /app
        - name: sparse-code
          mountPath: /usr/lib/sparse_framework
        - name: sparse-data
          mountPath: /data
        - name: sparse-run
          mountPath: /run/sparse
      volumes:
      - name: app-code
        hostPath:
          path: /opt/sparse/examples/split_learning
      - name: sparse-code
        hostPath:
          path: /opt/sparse/sparse_framework
      - name: sparse-data
        hostPath:
          path: /var/lib/sparse/data
      - name: sparse-run
        hostPath:
          path: /run/sparse
