---
apiVersion: v1
kind: Service
metadata:
  name: model-server
  namespace: sparse
  labels:
    app: model-server
spec:
  ports:
  - port: 50006
    protocol: TCP
  selector:
    app: model-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-server
  namespace: sparse
  labels:
    app: model-server
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: model-server
  template:
    metadata:
      labels:
        app: model-server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: sparse/model-server
                operator: In
                values:
                - "true"
      containers:
      - name: model-server
        image: split_learning
        imagePullPolicy: IfNotPresent
        command: ["python3"]
        args: ["model_server.py"]
        volumeMounts:
        - name: app-code
          mountPath: /app
        - name: sparse-code
          mountPath: /usr/lib/sparse_framework
      volumes:
      - name: app-code
        hostPath:
          path: /opt/sparse/examples/split_learning
      - name: sparse-code
        hostPath:
          path: /opt/sparse/sparse_framework
