---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sparse-monitor
  namespace: sparse
  labels:
    app: sparse-monitor
spec:
  selector:
    matchLabels:
      app: sparse-monitor
  template:
    metadata:
      labels:
        app: sparse-monitor
    spec:
      hostNetwork: true
      containers:
      - name: sparse-monitor
        image: sparse/pytorch
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: sparse-code
          mountPath: /usr/lib/sparse_framework
        - name: sparse-run
          mountPath: /run/sparse
        - name: sparse-stats
          mountPath: /data/stats
      volumes:
      - name: sparse-code
        hostPath:
          path: /opt/sparse/sparse_framework
      - name: sparse-stats
        hostPath:
          path: /var/lib/sparse/stats
      - name: sparse-run
        hostPath:
          path: /run/sparse
