---
apiVersion: batch/v1
kind: Job
metadata:
  name: splitnn-aio
  namespace: sparse
  labels:
    app: splitnn-aio
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: sparse/node
                operator: In
                values:
                - aio
              - key: kubernetes.io/arch
                operator: In
                values:
                - "amd64"
      containers:
      - name: splitnn-aio
        image: anterondocker/splitnn:pytorch
        imagePullPolicy: IfNotPresent
        env:
        - name: SPARSE_MODEL_SERVER_ADDRESS
          value: "model-server"
        command: ["python3"]
        args:
        - "aio.py"
        - "--suite"
        - "$SPARSE_SUITE"
        - "--model"
        - "$SPARSE_MODEL"
        - "--dataset"
        - "$SPARSE_DATASET"
        - "--batch-size"
        - "$SPARSE_BATCH_SIZE"
        - "--batches"
        - "$SPARSE_BATCHES"
        - "--epochs"
        - "$SPARSE_EPOCHS"
        volumeMounts:
        - name: app-code
          mountPath: /app
        - name: sparse-code
          mountPath: /usr/lib/sparse_framework
        - name: sparse-data
          mountPath: /data
        - name: sparse-run
          mountPath: /run/sparse
      restartPolicy: Never
      volumes:
      - name: app-code
        hostPath:
          path: /opt/sparse/examples/splitnn
      - name: sparse-code
        hostPath:
          path: /opt/sparse/sparse_framework
      - name: sparse-data
        hostPath:
          path: /var/lib/sparse/data
      - name: sparse-run
        hostPath:
          path: /run/sparse
---
apiVersion: batch/v1
kind: Job
metadata:
  name: splitnn-aio
  namespace: sparse
  labels:
    app: splitnn-aio
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: sparse/node
                operator: In
                values:
                - aio
              - key: kubernetes.io/arch
                operator: In
                values:
                - "arm64"
      containers:
      - name: splitnn-aio
        image: anterondocker/splitnn:l4t-pytorch
        imagePullPolicy: IfNotPresent
        env:
        - name: SPARSE_MODEL_SERVER_ADDRESS
          value: "model-server"
        command: ["python3"]
        args:
        - "aio.py"
        - "--suite"
        - "$SPARSE_SUITE"
        - "--model"
        - "$SPARSE_MODEL"
        - "--dataset"
        - "$SPARSE_DATASET"
        - "--batch-size"
        - "$SPARSE_BATCH_SIZE"
        - "--batches"
        - "$SPARSE_BATCHES"
        - "--epochs"
        - "$SPARSE_EPOCHS"
        volumeMounts:
        - name: app-code
          mountPath: /app
        - name: sparse-code
          mountPath: /usr/lib/sparse_framework
        - name: sparse-data
          mountPath: /data
        - name: sparse-run
          mountPath: /run/sparse
      restartPolicy: Never
      volumes:
      - name: app-code
        hostPath:
          path: /opt/sparse/examples/splitnn
      - name: sparse-code
        hostPath:
          path: /opt/sparse/sparse_framework
      - name: sparse-data
        hostPath:
          path: /var/lib/sparse/data
      - name: sparse-run
        hostPath:
          path: /run/sparse
