---
apiVersion: batch/v1
kind: Job
metadata:
  name: splitnn-client
  namespace: sparse
  labels:
    app: splitnn-client
spec:
  parallelism: $SPARSE_NO_DATASOURCES
  template:
    metadata:
      labels:
        app: splitnn-client
    spec:
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: sparse/node
                operator: In
                values:
                - datasource
                - aio
      containers:
      - name: splitnn-client
        image: sparse/splitnn
        imagePullPolicy: IfNotPresent
        env:
        - name: MASTER_UPSTREAM_HOST
          value: "$SPARSE_DATASOURCE_DOWNSTREAM_HOST"
        - name: MASTER_UPSTREAM_PORT
          value: "$SPARSE_DATASOURCE_DOWNSTREAM_PORT"
        - name: SPARSE_MODEL_SERVER_ADDRESS
          value: "model-server"
        command: ["python3"]
        args:
        - "client.py"
        - "--application"
        - "$SPARSE_APPLICATION"
        - "--suite"
        - "$SPARSE_SUITE"
        - "--model"
        - "$SPARSE_MODEL"
        - "--dataset"
        - "$SPARSE_DATASET"
        - "--batch-size"
        - "$SPARSE_BATCH_SIZE"
        - "--batches"
        - "$SPARSE_BATCHES"
        - "--epochs"
        - "$SPARSE_EPOCHS"
        resources:
          limits:
            cpu: "$SPARSE_DATASOURCE_CPU_LIMIT"
              # Adding memory limitations restrics using swap
              #            memory: "$SPARSE_DATASOURCE_MEMORY_LIMIT"
        volumeMounts:
        - name: app-code
          mountPath: /app
        - name: sparse-code
          mountPath: /usr/lib/sparse_framework
        - name: sparse-data
          mountPath: /data
        - name: sparse-run
          mountPath: /run/sparse
      volumes:
      - name: app-code
        hostPath:
          path: /opt/sparse/examples/splitnn
      - name: sparse-code
        hostPath:
          path: /opt/sparse/sparse_framework
      - name: sparse-data
        hostPath:
          path: /var/lib/sparse/data
      - name: sparse-run
        hostPath:
          path: /run/sparse
