---
apiVersion: v1
kind: Service
metadata:
  name: splitnn-intermediate
  namespace: sparse
  labels:
    app: splitnn-intermediate
spec:
  ports:
  - port: 50008
    protocol: TCP
  selector:
    app: splitnn-intermediate

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: splitnn-intermediate
  namespace: sparse
  labels:
    app: splitnn-intermediate
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: splitnn-intermediate
  template:
    metadata:
      labels:
        app: splitnn-intermediate
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: sparse/node
                operator: In
                values:
                - intermediate
                - aio
      containers:
      - name: splitnn-intermediate
        image: sparse/splitnn
        imagePullPolicy: IfNotPresent
        env:
        - name: MASTER_UPSTREAM_HOST
          value: "splitnn-worker"
        - name: WORKER_LISTEN_ADDRESS
          value: "0.0.0.0"
        - name: WORKER_LISTEN_PORT
          value: "50008"
        - name: SPARSE_MODEL_SERVER_ADDRESS
          value: "model-server"
        command: ["python3"]
        args:
        - "intermediate.py"
        - "--application"
        - "$SPARSE_APPLICATION"
        - "--suite"
        - "$SPARSE_SUITE"
        - "--model"
        - "$SPARSE_MODEL"
        - "--dataset"
        - "$SPARSE_DATASET"
        - "--batch-size"
        - "$SPARSE_BATCH_SIZE"
        - "--batches"
        - "$SPARSE_BATCHES"
        - "--epochs"
        - "$SPARSE_EPOCHS"
        volumeMounts:
        - name: app-code
          mountPath: /app
        - name: sparse-code
          mountPath: /usr/lib/sparse_framework
        - name: sparse-run
          mountPath: /run/sparse
      volumes:
      - name: app-code
        hostPath:
          path: /opt/sparse/examples/splitnn
      - name: sparse-code
        hostPath:
          path: /opt/sparse/sparse_framework
      - name: sparse-run
        hostPath:
          path: /run/sparse
