---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: splitnn-worker
  namespace: sparse
  labels:
    app: splitnn-worker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: splitnn-worker
  template:
    metadata:
      labels:
        app: splitnn-worker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: sparse/node
                operator: In
                values:
                - worker
                - aio
      containers:
      - name: splitnn-worker
        image: sparse/splitnn
        imagePullPolicy: IfNotPresent
        env:
        - name: WORKER_LISTEN_ADDRESS
          value: "0.0.0.0"
        - name: SPARSE_MODEL_SERVER_ADDRESS
          value: "model-server"
        command: ["python3"]
        args:
        - "worker.py"
        - "--use-scheduling"
        - "$SPARSE_USE_SCHEDULING"
        - "--use-batching"
        - "$SPARSE_USE_BATCHING"
        volumeMounts:
        - name: app-code
          mountPath: /app
        - name: sparse-code
          mountPath: /usr/lib/sparse_framework
        - name: sparse-run
          mountPath: /run/sparse
        - name: sparse-stats
          mountPath: /data/stats
      volumes:
      - name: app-code
        hostPath:
          path: /opt/sparse/examples/splitnn
      - name: sparse-code
        hostPath:
          path: /opt/sparse/sparse_framework
      - name: sparse-run
        hostPath:
          path: /run/sparse
      - name: sparse-stats
        hostPath:
          path: /var/lib/sparse/stats
