---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deprune-worker
  namespace: sparse
  labels:
    app: deprune-worker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: deprune-worker
  template:
    metadata:
      labels:
        app: deprune-worker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: sparse/node
                operator: In
                values:
                - worker
                - aio
      containers:
      - name: deprune-worker
        image: split_inference
        imagePullPolicy: IfNotPresent
        env:
        - name: WORKER_LISTEN_ADDRESS
          value: "0.0.0.0"
        - name: SPARSE_MODEL_SERVER_ADDRESS
          value: "model-server"
        command: ["python3"]
        args:
        - "worker.py"
        - "--application"
        - "$SPARSE_APPLICATION"
        - "--suite"
        - "$SPARSE_SUITE"
        - "--model"
        - "$SPARSE_MODEL"
        - "--dataset"
        - "$SPARSE_DATASET"
        - "--batch-size"
        - "$SPARSE_BATCH_SIZE"
        - "--batches"
        - "$SPARSE_BATCHES"
        - "--deprune-props"
        - "$SPARSE_DEPRUNE_PROPS"
        - "--feature_compression_factor"
        - "$SPARSE_FEATURE_COMPRESSION_FACTOR"
        - "--resolution_compression_factor"
        - "$SPARSE_RESOLUTION_COMPRESSION_FACTOR"
        volumeMounts:
        - name: app-code
          mountPath: /app
        - name: sparse-code
          mountPath: /usr/lib/sparse_framework
        - name: sparse-data
          mountPath: /data
        - name: sparse-run
          mountPath: /run/sparse
      volumes:
      - name: app-code
        hostPath:
          path: /opt/sparse/examples/deprune
      - name: sparse-code
        hostPath:
          path: /opt/sparse/sparse_framework
      - name: sparse-data
        hostPath:
          path: /var/lib/sparse/data
      - name: sparse-run
        hostPath:
          path: /run/sparse
